### ISSUE TITLE
improve form validation ux

### ISSUE THREAD

**Issue by mmnoo** [globalmangrovewatch/gmw-users#162]
summarize errors by submit button

**Comment by alanjleonard** [comment]
![image](https://user-images.githubusercontent.com/35936230/179011278-151d828f-80c5-4bf3-981d-c90eb2b8a9f5.png)


After the user clicks "save" if there is any validation preventing the form from being saved, show [an alert](https://mui.com/material-ui/react-alert/#outlined) under the section navigation (see mockup).

Use this MUI component https://mui.com/material-ui/react-alert/#outlined

I think for now, we can use one generic error message since it's only required fields not being filled out that would prevent them from saving the form.
