### ISSUE TITLE
Quick QA for demo

### ISSUE THREAD

**Issue by mmnoo** [globalmangrovewatch/gmw-users#163]
List undone things, known bugs

QA login, signup, new site, edit site, question sections 1-4, look and feel stuff

Extra check after form edit: hit refresh to make sure sumbitted values went to the api and get pulled and loaded correctly again into the front end

**Comment by mmnoo** [comment]
https://gmw-users-test.herokuapp.com/

**Comment by mmnoo** [comment]
Undone things off the top of my head:

- section 5+
- editing/creating/deleting landscapes and orgs
- extra details on sites list card, and landscapes list card

**Comment by alanjleonard** [comment]
Gerneral overall aestic is still in progress which includes, but not limited to:
- Links will be styled better
- Hover states on desktop
- More informative Site cards
- Logo image
- Placeholder text in inputs should be lighter, as to not confuse with an answer from the user

Creating a new site:
- New site form should have all required fields in section 1
- After creating a new site, should be navigated to section two. Since all of section 1 will be complete when creating the site.

All sections: 
- Submit button should be more informative. something like "Save change", "Save and continue to next section"
- Should prompt before navigating away from an unsaved form
- Don't show errors until form is submitted. For example: When editing question 2.1, if you uncheck everything, the error `stakeholders field must have at least 1 items` is displayed.
- Pluralization in error messages

Section 1:
- z-index issue: Country dropdown goes under question 1.3 when the page is scrolled to the bottom. Can't select country. 
- z-index issue: file success upload is hidden by submit button container
- After success geojson file upload, nothing changed on the map
- Project start date can be after project end date

Section 2:
- None of the questions in section 2 are required.
- Stakeholder name are prepopulated with previously submitted values.
- - 1. Check some stakeholder
- - 2. Fill out the `name` field
- - 3. save and reload
- - 4. Uncheck a previously checked stakeholder
- - 5. check another one
- - 6. noticed that the `name` filed is populated with the value from the first field.
- Question 2.1 - can't click checkbox labels to select checkbox.
- Question 2.5 - should it be single choice? How can it be **Full Protection** _AND_ **Partial Protection**?

Section 3:
- Question 3.3 is not required

Section 4:
- Question 4.2 is not required.
- Answering "no" and clicking submit does not give confirmation toast of being saved. 
- Only some labels check/uncheck the associated boxes when clicked (after GEOLOGICAL EVENTS)?
- Font size mismatch on labels after GEOLOGICAL EVENTS.
- Error message not Human readable `causesOfDecline field must have at least 1 items`
- Pluralization in above error message, should be `1 item` (no `s`)
- Two asterisks on first `Magnitude of impact` dropdown, other options have one. Should have none since they're not required
- Question 4.3 is not required, but the app only shows confirmation of being saved when all of Q4.3 is complete
- After answering 'Yes' on question 4.1, if you change your anser to "no" it should also hide question 4.3.
